### ISSUE TITLE
CSS/Navigation

### ISSUE THREAD

**Issue by Senkua** [Senkua/Proffessional-Portfolio#3]
Add the links for navigation, Add images to each box and assign the proper spacing.

**Comment by yellowsamuray** [comment]
![47CE1E20-AC9E-4B8F-9D97-54FF2FD58D14](https://user-images.githubusercontent.com/31334367/235462300-4f0b69df-643c-4081-bf3b-730b05a08973.jpeg)

The div for class "row" is bleeding into the navigation. I tried disabling the height in css for class row and it fixed it. You might want to put it into consideration.

![909CDA6F-8F18-41CC-9D5E-76E83ED32F5F](https://user-images.githubusercontent.com/31334367/235462757-b098b4fe-8e77-4a0e-87b2-256a0aa8fdbb.jpeg)

You might also want to put more margin into the navigation bar.

**Comment by yellowsamuray** [comment]
![9A70F480-AD34-498B-ACD4-0BCB74CD84ED](https://user-images.githubusercontent.com/31334367/235463587-b59dd332-50ef-48ac-b607-14f3041b407c.jpeg)

You should add padding instead. You can test 20-30px; or to your liking.

**Comment by Senkua** [comment]
alright I'll check this out and most likely implement this, thanks!
